language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
   - vendor/bin/phpunit --coverage-clover=coverage.clover --configuration ./phpunit.xml.dist ./tests

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
