language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
   - phpunit --coverage-clover=coverage.clover --configuration ./phpunit.xml.dist ./tests

after_script:
 - php bin/codacycoverage clover build/logs/clover.xml
