language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration ./phpunit.xml.dist ./tests

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
